#Test pr

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'


pool:
  name: vs2017-win2016
steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false
  enabled: false

- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    workingDir: TestNPM
    verbose: false
    customCommand: run

- script: |
   echo 1
   
  displayName: 'Command Line Script echo1'

