#Test pr

trigger:
- master

pr:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'


pool:
  name: AlexselfhostedagentPool
steps:

- script: |
   echo 1
   
  displayName: 'Command Line Script echo1'

